### ISSUE TITLE
Not working - Old Cent OS 7.9.2009 system

### ISSUE THREAD

**Issue by furicle** [ocristopfer/cockpit-sensors-old#16]
I have cockpit installed and working.
I have lm-sensors installed, and `sensors` returns the temps from the CPUs

But the "Sensors" section of Cockpit shows an error 
⚠️ sensors: invalid option -- 'j'

`man sensors` shows no -j option.

Can this be worked around?

**Comment by ocristopfer** [comment]
oops, good afternoon.
Can you tell me what version of lm-sensors ?
I used the -j argument because lm-sensors returns a json and is easier to work with.

What I would have to do is test if there is a return and if there is not, take the raw and try to treat it, but that would be a lot of work to implement.
Because basically I would have to be able to convert raw to json.

**Comment by furicle** [comment]
This machine shows
`Name        : lm_sensors
Arch        : x86_64
Version     : 3.4.0
Release     : 8.20160601gitf9185e5.el7`

If it's a bunch of work, then I think just documenting the minimum requirements is reasonable... 
Cent 7 is out of support now I believe.

**Comment by ocristopfer** [comment]
so I googled here and saw that the -j argument was only created in 2017 and it turned out that it only works on lm-sensors
versions 3.5 or greater. While I don't have the time to make this adjustment, I'll leave the minimum version in the readme, being 3.5.0.
I'm sorry.

https://github.com/lm-sensors/lm-sensors/blob/master/prog/sensors/main.c

**Comment by furicle** [comment]
Nothing to be sorry about!
Thanks for the work you've done here.

**Comment by ocristopfer** [comment]
In the new version (1.2) of the plugin, it adds support for old versions of lm-sensors.
Download the latest version and test please.

**Comment by furicle** [comment]
Will do!  Might be a week or so.

**Comment by furicle** [comment]
Found a handy box rather than wait.

Works!

Thank you!

[https://files.mastodon.social/media_attachments/files/109/423/345/646/647/960/small/d30ee34aaf4bdff9.png](url)
